-- ============================================================
--  Cr7watch — Ürün seed verisi (dosyalar/ ile birebir, OTOMATİK üretildi)
--  schema.sql + seed-brands.sql çalıştırıldıktan SONRA bunu çalıştırın.
--  Yeniden çalıştırılabilir (idempotent): mevcut seed ürünleri tazeler.
-- ============================================================

-- 1) Ürünler (slug üzerinden upsert)
insert into products (brand_slug, name, slug, series, gender, price, description, is_featured, is_active, sold) values
  ('audemars-piguet', 'Audemars Piguet Erkek 1', 'ap-erkek-1', 'Royal Oak', 'erkek', NULL, 'Audemars Piguet Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', true, true, false),
  ('audemars-piguet', 'Audemars Piguet Erkek 2', 'ap-erkek-2', 'Royal Oak', 'erkek', NULL, 'Audemars Piguet Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('audemars-piguet', 'Audemars Piguet Erkek 3', 'ap-erkek-3', 'Royal Oak', 'erkek', NULL, 'Audemars Piguet Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('audemars-piguet', 'Audemars Piguet Erkek 4', 'ap-erkek-4', 'Royal Oak', 'erkek', NULL, 'Audemars Piguet Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('audemars-piguet', 'Audemars Piguet Erkek 5', 'ap-erkek-5', 'Royal Oak', 'erkek', NULL, 'Audemars Piguet Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('audemars-piguet', 'Audemars Piguet Erkek 6', 'ap-erkek-6', 'Royal Oak', 'erkek', NULL, 'Audemars Piguet Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('audemars-piguet', 'Audemars Piguet Bayan 1', 'ap-bayan-1', 'Royal Oak', 'bayan', NULL, 'Audemars Piguet Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', true, true, false),
  ('audemars-piguet', 'Audemars Piguet Bayan 2', 'ap-bayan-2', 'Royal Oak', 'bayan', NULL, 'Audemars Piguet Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('audemars-piguet', 'Audemars Piguet Bayan 3', 'ap-bayan-3', 'Royal Oak', 'bayan', NULL, 'Audemars Piguet Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('audemars-piguet', 'Audemars Piguet Bayan 4', 'ap-bayan-4', 'Royal Oak', 'bayan', NULL, 'Audemars Piguet Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('bulgari', 'Bulgari Bayan 1', 'bulgari-bayan-1', NULL, 'bayan', NULL, 'Bulgari Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('bulgari', 'Bulgari Bayan 2', 'bulgari-bayan-2', NULL, 'bayan', NULL, 'Bulgari Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('bulgari', 'Bulgari Bayan 3', 'bulgari-bayan-3', NULL, 'bayan', NULL, 'Bulgari Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('bulgari', 'Bulgari Bayan 4', 'bulgari-bayan-4', NULL, 'bayan', NULL, 'Bulgari Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Erkek 1', 'cartier-erkek-1', NULL, 'erkek', NULL, 'Cartier Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', true, true, false),
  ('cartier', 'Cartier Erkek 2', 'cartier-erkek-2', NULL, 'erkek', NULL, 'Cartier Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Erkek 3', 'cartier-erkek-3', NULL, 'erkek', NULL, 'Cartier Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Erkek 4', 'cartier-erkek-4', NULL, 'erkek', NULL, 'Cartier Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Erkek 5', 'cartier-erkek-5', NULL, 'erkek', NULL, 'Cartier Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Erkek 6', 'cartier-erkek-6', NULL, 'erkek', NULL, 'Cartier Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Erkek 7', 'cartier-erkek-7', NULL, 'erkek', NULL, 'Cartier Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Erkek 8', 'cartier-erkek-8', NULL, 'erkek', NULL, 'Cartier Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Erkek 9', 'cartier-erkek-9', NULL, 'erkek', NULL, 'Cartier Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Erkek 10', 'cartier-erkek-10', NULL, 'erkek', NULL, 'Cartier Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Erkek 11', 'cartier-erkek-11', NULL, 'erkek', NULL, 'Cartier Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Erkek 12', 'cartier-erkek-12', NULL, 'erkek', NULL, 'Cartier Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Bayan 1', 'cartier-bayan-1', NULL, 'bayan', NULL, 'Cartier Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', true, true, false),
  ('cartier', 'Cartier Bayan 2', 'cartier-bayan-2', NULL, 'bayan', NULL, 'Cartier Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Bayan 3', 'cartier-bayan-3', NULL, 'bayan', NULL, 'Cartier Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Bayan 4', 'cartier-bayan-4', NULL, 'bayan', NULL, 'Cartier Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Bayan 5', 'cartier-bayan-5', NULL, 'bayan', NULL, 'Cartier Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Bayan 6', 'cartier-bayan-6', NULL, 'bayan', NULL, 'Cartier Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Bayan 7', 'cartier-bayan-7', NULL, 'bayan', NULL, 'Cartier Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Bayan 8', 'cartier-bayan-8', NULL, 'bayan', NULL, 'Cartier Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Bayan 9', 'cartier-bayan-9', NULL, 'bayan', NULL, 'Cartier Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Bayan 10', 'cartier-bayan-10', NULL, 'bayan', NULL, 'Cartier Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Bayan 11', 'cartier-bayan-11', NULL, 'bayan', NULL, 'Cartier Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Bayan 12', 'cartier-bayan-12', NULL, 'bayan', NULL, 'Cartier Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Bayan 13', 'cartier-bayan-13', NULL, 'bayan', NULL, 'Cartier Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Bayan 14', 'cartier-bayan-14', NULL, 'bayan', NULL, 'Cartier Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Bayan 15', 'cartier-bayan-15', NULL, 'bayan', NULL, 'Cartier Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Bayan 16', 'cartier-bayan-16', NULL, 'bayan', NULL, 'Cartier Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('cartier', 'Cartier Bayan 17', 'cartier-bayan-17', NULL, 'bayan', NULL, 'Cartier Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('citizen', 'Citizen 1', 'citizen-1', NULL, 'unisex', NULL, 'Citizen — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('citizen', 'Citizen 2', 'citizen-2', NULL, 'unisex', NULL, 'Citizen — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex ETA Erkek 1', 'eta-rolex-1', 'ETA', 'erkek', NULL, 'Rolex ETA Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', true, true, false),
  ('frank-muller', 'Frank Müller 1', 'frank-muller-1', NULL, 'erkek', NULL, 'Frank Müller — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('frank-muller', 'Frank Müller 2', 'frank-muller-2', NULL, 'erkek', NULL, 'Frank Müller — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('frank-muller', 'Frank Müller 3', 'frank-muller-3', NULL, 'erkek', NULL, 'Frank Müller — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('frank-muller', 'Frank Müller 4', 'frank-muller-4', NULL, 'erkek', NULL, 'Frank Müller — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('frank-muller', 'Frank Müller 5', 'frank-muller-5', NULL, 'erkek', NULL, 'Frank Müller — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('frank-muller', 'Frank Müller 6', 'frank-muller-6', NULL, 'erkek', NULL, 'Frank Müller — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('frank-muller', 'Frank Müller 7', 'frank-muller-7', NULL, 'erkek', NULL, 'Frank Müller — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('frank-muller', 'Frank Müller 8', 'frank-muller-8', NULL, 'erkek', NULL, 'Frank Müller — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('frank-muller', 'Frank Müller 9', 'frank-muller-9', NULL, 'erkek', NULL, 'Frank Müller — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('frank-muller', 'Frank Müller 10', 'frank-muller-10', NULL, 'erkek', NULL, 'Frank Müller — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('frank-muller', 'Frank Müller 11', 'frank-muller-11', NULL, 'erkek', NULL, 'Frank Müller — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('frank-muller', 'Frank Müller 12', 'frank-muller-12', NULL, 'erkek', NULL, 'Frank Müller — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('frank-muller', 'Frank Müller 13', 'frank-muller-13', NULL, 'erkek', NULL, 'Frank Müller — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('frank-muller', 'Frank Müller 14', 'frank-muller-14', NULL, 'erkek', NULL, 'Frank Müller — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('frank-muller', 'Frank Müller 15', 'frank-muller-15', NULL, 'erkek', NULL, 'Frank Müller — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('gc', 'GC Erkek 1', 'gc-erkek-1', NULL, 'erkek', NULL, 'GC Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('invicta', 'Invicta 1', 'invicta-1', NULL, 'erkek', NULL, 'Invicta — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('invicta', 'Invicta 2', 'invicta-2', NULL, 'erkek', NULL, 'Invicta — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('invicta', 'Invicta 3', 'invicta-3', NULL, 'erkek', NULL, 'Invicta — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('jaeger-lecoultre', 'Jaeger-LeCoultre 1', 'jaeger-1', NULL, 'erkek', NULL, 'Jaeger-LeCoultre — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('jaeger-lecoultre', 'Jaeger-LeCoultre 2', 'jaeger-2', NULL, 'erkek', NULL, 'Jaeger-LeCoultre — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('longines', 'Longines 1', 'longin-1', NULL, 'unisex', NULL, 'Longines — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('longines', 'Longines 2', 'longin-2', NULL, 'unisex', NULL, 'Longines — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('longines', 'Longines 3', 'longin-3', NULL, 'unisex', NULL, 'Longines — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('longines', 'Longines 4', 'longin-4', NULL, 'unisex', NULL, 'Longines — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('longines', 'Longines 5', 'longin-5', NULL, 'unisex', NULL, 'Longines — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('longines', 'Longines 6', 'longin-6', NULL, 'unisex', NULL, 'Longines — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('longines', 'Longines 7', 'longin-7', NULL, 'unisex', NULL, 'Longines — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('longines', 'Longines 8', 'longin-8', NULL, 'unisex', NULL, 'Longines — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('longines', 'Longines 9', 'longin-9', NULL, 'unisex', NULL, 'Longines — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('longines', 'Longines 10', 'longin-10', NULL, 'unisex', NULL, 'Longines — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('oris', 'Oris 1', 'oris-1', NULL, 'erkek', NULL, 'Oris — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('patek-philippe', 'Patek Philippe Erkek 1', 'patek-1', NULL, 'erkek', NULL, 'Patek Philippe Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', true, true, false),
  ('patek-philippe', 'Patek Philippe Erkek 2', 'patek-2', NULL, 'erkek', NULL, 'Patek Philippe Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('patek-philippe', 'Patek Philippe Erkek 3', 'patek-3', NULL, 'erkek', NULL, 'Patek Philippe Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('patek-philippe', 'Patek Philippe Erkek 4', 'patek-4', NULL, 'erkek', NULL, 'Patek Philippe Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('patek-philippe', 'Patek Philippe Erkek 5', 'patek-5', NULL, 'erkek', NULL, 'Patek Philippe Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('patek-philippe', 'Patek Philippe Erkek 6', 'patek-6', NULL, 'erkek', NULL, 'Patek Philippe Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('patek-philippe', 'Patek Philippe Klasik 1', 'patek-klasik-1', 'Klasik', 'erkek', NULL, 'Patek Philippe Klasik — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', true, true, false),
  ('patek-philippe', 'Patek Philippe Klasik 2', 'patek-klasik-2', 'Klasik', 'erkek', NULL, 'Patek Philippe Klasik — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('patek-philippe', 'Patek Philippe Klasik 3', 'patek-klasik-3', 'Klasik', 'erkek', NULL, 'Patek Philippe Klasik — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('patek-philippe', 'Patek Philippe Klasik 4', 'patek-klasik-4', 'Klasik', 'erkek', NULL, 'Patek Philippe Klasik — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('patek-philippe', 'Patek Philippe Bayan 1', 'patek-bayan-1', NULL, 'bayan', NULL, 'Patek Philippe Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', true, true, false),
  ('patek-philippe', 'Patek Philippe Bayan 2', 'patek-bayan-2', NULL, 'bayan', NULL, 'Patek Philippe Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('patek-philippe', 'Patek Philippe Bayan 3', 'patek-bayan-3', NULL, 'bayan', NULL, 'Patek Philippe Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('patek-philippe', 'Patek Philippe İnce Kasa 1', 'patek-ince-kasa-ppf-1', 'İnce Kasa', 'erkek', NULL, 'Patek Philippe İnce Kasa — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rado', 'Rado 1', 'rado-1', NULL, 'unisex', NULL, 'Rado — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('richard-mille', 'Richard Mille 1', 'richard-mille-1', NULL, 'erkek', NULL, 'Richard Mille — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('richard-mille', 'Richard Mille 2', 'richard-mille-2', NULL, 'erkek', NULL, 'Richard Mille — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('richard-mille', 'Richard Mille 3', 'richard-mille-3', NULL, 'erkek', NULL, 'Richard Mille — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Erkek 1', 'rolex-1', NULL, 'erkek', NULL, 'Rolex Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Erkek 2', 'rolex-2', NULL, 'erkek', NULL, 'Rolex Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Erkek 3', 'rolex-3', NULL, 'erkek', NULL, 'Rolex Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Erkek 4', 'rolex-4', NULL, 'erkek', NULL, 'Rolex Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Erkek 5', 'rolex-5', NULL, 'erkek', NULL, 'Rolex Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Erkek 6', 'rolex-6', NULL, 'erkek', NULL, 'Rolex Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Erkek 7', 'rolex-7', NULL, 'erkek', NULL, 'Rolex Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Erkek 8', 'rolex-8', NULL, 'erkek', NULL, 'Rolex Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Erkek 9', 'rolex-9', NULL, 'erkek', NULL, 'Rolex Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Erkek 10', 'rolex-10', NULL, 'erkek', NULL, 'Rolex Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Erkek 11', 'rolex-11', NULL, 'erkek', NULL, 'Rolex Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Erkek 12', 'rolex-12', NULL, 'erkek', NULL, 'Rolex Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Erkek 13', 'rolex-13', NULL, 'erkek', NULL, 'Rolex Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Erkek 14', 'rolex-14', NULL, 'erkek', NULL, 'Rolex Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Erkek 15', 'rolex-15', NULL, 'erkek', NULL, 'Rolex Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Erkek 16', 'rolex-16', NULL, 'erkek', NULL, 'Rolex Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Bayan 36 1', 'rolex-bayan-36-1', '36mm', 'bayan', NULL, 'Rolex Bayan 36 — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Bayan 36 2', 'rolex-bayan-36-2', '36mm', 'bayan', NULL, 'Rolex Bayan 36 — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Bayan 36 3', 'rolex-bayan-36-3', '36mm', 'bayan', NULL, 'Rolex Bayan 36 — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 1', 'rolex-yz-erkek-1', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 2', 'rolex-yz-erkek-2', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 3', 'rolex-yz-erkek-3', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 4', 'rolex-yz-erkek-4', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 5', 'rolex-yz-erkek-5', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 6', 'rolex-yz-erkek-6', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 7', 'rolex-yz-erkek-7', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 8', 'rolex-yz-erkek-8', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 9', 'rolex-yz-erkek-9', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 10', 'rolex-yz-erkek-10', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 11', 'rolex-yz-erkek-11', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 12', 'rolex-yz-erkek-12', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 13', 'rolex-yz-erkek-13', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 14', 'rolex-yz-erkek-14', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 15', 'rolex-yz-erkek-15', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 16', 'rolex-yz-erkek-16', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 17', 'rolex-yz-erkek-17', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 18', 'rolex-yz-erkek-18', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex YZ Erkek 19', 'rolex-yz-erkek-19', 'YZ', 'erkek', NULL, 'Rolex YZ Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Bayan 31 1', 'rolex-bayan-31-1', '31mm', 'bayan', NULL, 'Rolex Bayan 31 — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Bayan 31 2', 'rolex-bayan-31-2', '31mm', 'bayan', NULL, 'Rolex Bayan 31 — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Bayan 31 3', 'rolex-bayan-31-3', '31mm', 'bayan', NULL, 'Rolex Bayan 31 — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Bayan 31 4', 'rolex-bayan-31-4', '31mm', 'bayan', NULL, 'Rolex Bayan 31 — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('rolex', 'Rolex Bayan 31 5', 'rolex-bayan-31-5', '31mm', 'bayan', NULL, 'Rolex Bayan 31 — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('aksesuar', 'Saat Kutusu 1', 'saat-kutulari-1', 'Saat Kutusu', 'unisex', NULL, 'Saat Kutusu — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('aksesuar', 'Saat Kutusu 2', 'saat-kutulari-2', 'Saat Kutusu', 'unisex', NULL, 'Saat Kutusu — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('aksesuar', 'Saat Kutusu 3', 'saat-kutulari-3', 'Saat Kutusu', 'unisex', NULL, 'Saat Kutusu — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('aksesuar', 'Saat Kutusu 4', 'saat-kutulari-4', 'Saat Kutusu', 'unisex', NULL, 'Saat Kutusu — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('aksesuar', 'Saat Kutusu 5', 'saat-kutulari-5', 'Saat Kutusu', 'unisex', NULL, 'Saat Kutusu — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('seven-friday', 'Seven Friday 1', 'seven-friday-1', NULL, 'erkek', NULL, 'Seven Friday — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('seven-friday', 'Seven Friday 2', 'seven-friday-2', NULL, 'erkek', NULL, 'Seven Friday — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('seven-friday', 'Seven Friday 3', 'seven-friday-3', NULL, 'erkek', NULL, 'Seven Friday — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('seven-friday', 'Seven Friday 4', 'seven-friday-4', NULL, 'erkek', NULL, 'Seven Friday — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('seven-friday', 'Seven Friday 5', 'seven-friday-5', NULL, 'erkek', NULL, 'Seven Friday — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('seven-friday', 'Seven Friday 6', 'seven-friday-6', NULL, 'erkek', NULL, 'Seven Friday — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('tag-heuer', 'Tag Heuer 1', 'tag-1', NULL, 'erkek', NULL, 'Tag Heuer — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('tag-heuer', 'Tag Heuer 2', 'tag-2', NULL, 'erkek', NULL, 'Tag Heuer — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('tag-heuer', 'Tag Heuer 3', 'tag-3', NULL, 'erkek', NULL, 'Tag Heuer — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('tag-heuer', 'Tag Heuer 4', 'tag-4', NULL, 'erkek', NULL, 'Tag Heuer — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('tag-heuer', 'Tag Heuer 5', 'tag-5', NULL, 'erkek', NULL, 'Tag Heuer — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('tag-heuer', 'Tag Heuer 6', 'tag-6', NULL, 'erkek', NULL, 'Tag Heuer — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('tudor', 'Tudor 1', 'tudor-1', NULL, 'erkek', NULL, 'Tudor — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('tudor', 'Tudor 2', 'tudor-2', NULL, 'erkek', NULL, 'Tudor — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('tudor', 'Tudor 3', 'tudor-3', NULL, 'erkek', NULL, 'Tudor — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('tudor', 'Tudor 4', 'tudor-4', NULL, 'erkek', NULL, 'Tudor — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('tudor', 'Tudor 5', 'tudor-5', NULL, 'erkek', NULL, 'Tudor — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('tudor', 'Tudor 6', 'tudor-6', NULL, 'erkek', NULL, 'Tudor — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('tudor', 'Tudor 7', 'tudor-7', NULL, 'erkek', NULL, 'Tudor — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('tudor', 'Tudor 8', 'tudor-8', NULL, 'erkek', NULL, 'Tudor — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('tudor', 'Tudor 9', 'tudor-9', NULL, 'erkek', NULL, 'Tudor — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('tudor', 'Tudor 10', 'tudor-10', NULL, 'erkek', NULL, 'Tudor — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 1', 'ulyse-nardin-1', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 2', 'ulyse-nardin-2', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 3', 'ulyse-nardin-3', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 4', 'ulyse-nardin-4', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 5', 'ulyse-nardin-5', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 6', 'ulyse-nardin-6', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 7', 'ulyse-nardin-7', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 8', 'ulyse-nardin-8', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 9', 'ulyse-nardin-9', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 10', 'ulyse-nardin-10', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 11', 'ulyse-nardin-11', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 12', 'ulyse-nardin-12', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 13', 'ulyse-nardin-13', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 14', 'ulyse-nardin-14', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 15', 'ulyse-nardin-15', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 16', 'ulyse-nardin-16', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 17', 'ulyse-nardin-17', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 18', 'ulyse-nardin-18', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 19', 'ulyse-nardin-19', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('ulysse-nardin', 'Ulysse Nardin 20', 'ulyse-nardin-20', NULL, 'erkek', NULL, 'Ulysse Nardin — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('versace', 'Versace Bayan 1', 'versace-bayan-1', NULL, 'bayan', NULL, 'Versace Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('versace', 'Versace Bayan 2', 'versace-bayan-2', NULL, 'bayan', NULL, 'Versace Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('versace', 'Versace Bayan 3', 'versace-bayan-3', NULL, 'bayan', NULL, 'Versace Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('versace', 'Versace Bayan 4', 'versace-bayan-4', NULL, 'bayan', NULL, 'Versace Bayan — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('versace', 'Versace Erkek 1', 'versace-erkek-1', NULL, 'erkek', NULL, 'Versace Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('versace', 'Versace Erkek 2', 'versace-erkek-2', NULL, 'erkek', NULL, 'Versace Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('versace', 'Versace Erkek 3', 'versace-erkek-3', NULL, 'erkek', NULL, 'Versace Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('versace', 'Versace Erkek 4', 'versace-erkek-4', NULL, 'erkek', NULL, 'Versace Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('versace', 'Versace Erkek 5', 'versace-erkek-5', NULL, 'erkek', NULL, 'Versace Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('versace', 'Versace Erkek 6', 'versace-erkek-6', NULL, 'erkek', NULL, 'Versace Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('versace', 'Versace Erkek 7', 'versace-erkek-7', NULL, 'erkek', NULL, 'Versace Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('versace', 'Versace Erkek 8', 'versace-erkek-8', NULL, 'erkek', NULL, 'Versace Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('versace', 'Versace Erkek 9', 'versace-erkek-9', NULL, 'erkek', NULL, 'Versace Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('versace', 'Versace Erkek 10', 'versace-erkek-10', NULL, 'erkek', NULL, 'Versace Erkek — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('washaron', 'Washaron 1', 'washaron-1', NULL, 'unisex', NULL, 'Washaron — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('washaron', 'Washaron 2', 'washaron-2', NULL, 'unisex', NULL, 'Washaron — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('washaron', 'Washaron 3', 'washaron-3', NULL, 'unisex', NULL, 'Washaron — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('washaron', 'Washaron 4', 'washaron-4', NULL, 'unisex', NULL, 'Washaron — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('washaron', 'Washaron 5', 'washaron-5', NULL, 'unisex', NULL, 'Washaron — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('washaron', 'Washaron 6', 'washaron-6', NULL, 'unisex', NULL, 'Washaron — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('washaron', 'Washaron 7', 'washaron-7', NULL, 'unisex', NULL, 'Washaron — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('washaron', 'Washaron 8', 'washaron-8', NULL, 'unisex', NULL, 'Washaron — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('washaron', 'Washaron 9', 'washaron-9', NULL, 'unisex', NULL, 'Washaron — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false),
  ('washaron', 'Washaron 10', 'washaron-10', NULL, 'unisex', NULL, 'Washaron — Cr7watch koleksiyonundan, gerçek ürün fotoğraflarıyla. Farklı açılardan inceleyin; sipariş ve güncel fiyat için WhatsApp’tan yazın.', false, true, false)
on conflict (slug) do update set
  brand_slug = excluded.brand_slug,
  name = excluded.name,
  series = excluded.series,
  gender = excluded.gender,
  description = excluded.description,
  is_featured = excluded.is_featured,
  is_active = excluded.is_active;

-- 2) Görseller: bu ürünlerin eski görsellerini temizle, yenisini ekle
delete from product_images where product_id in (
  select id from products where slug in ('ap-erkek-1', 'ap-erkek-2', 'ap-erkek-3', 'ap-erkek-4', 'ap-erkek-5', 'ap-erkek-6', 'ap-bayan-1', 'ap-bayan-2', 'ap-bayan-3', 'ap-bayan-4', 'bulgari-bayan-1', 'bulgari-bayan-2', 'bulgari-bayan-3', 'bulgari-bayan-4', 'cartier-erkek-1', 'cartier-erkek-2', 'cartier-erkek-3', 'cartier-erkek-4', 'cartier-erkek-5', 'cartier-erkek-6', 'cartier-erkek-7', 'cartier-erkek-8', 'cartier-erkek-9', 'cartier-erkek-10', 'cartier-erkek-11', 'cartier-erkek-12', 'cartier-bayan-1', 'cartier-bayan-2', 'cartier-bayan-3', 'cartier-bayan-4', 'cartier-bayan-5', 'cartier-bayan-6', 'cartier-bayan-7', 'cartier-bayan-8', 'cartier-bayan-9', 'cartier-bayan-10', 'cartier-bayan-11', 'cartier-bayan-12', 'cartier-bayan-13', 'cartier-bayan-14', 'cartier-bayan-15', 'cartier-bayan-16', 'cartier-bayan-17', 'citizen-1', 'citizen-2', 'eta-rolex-1', 'frank-muller-1', 'frank-muller-2', 'frank-muller-3', 'frank-muller-4', 'frank-muller-5', 'frank-muller-6', 'frank-muller-7', 'frank-muller-8', 'frank-muller-9', 'frank-muller-10', 'frank-muller-11', 'frank-muller-12', 'frank-muller-13', 'frank-muller-14', 'frank-muller-15', 'gc-erkek-1', 'invicta-1', 'invicta-2', 'invicta-3', 'jaeger-1', 'jaeger-2', 'longin-1', 'longin-2', 'longin-3', 'longin-4', 'longin-5', 'longin-6', 'longin-7', 'longin-8', 'longin-9', 'longin-10', 'oris-1', 'patek-1', 'patek-2', 'patek-3', 'patek-4', 'patek-5', 'patek-6', 'patek-klasik-1', 'patek-klasik-2', 'patek-klasik-3', 'patek-klasik-4', 'patek-bayan-1', 'patek-bayan-2', 'patek-bayan-3', 'patek-ince-kasa-ppf-1', 'rado-1', 'richard-mille-1', 'richard-mille-2', 'richard-mille-3', 'rolex-1', 'rolex-2', 'rolex-3', 'rolex-4', 'rolex-5', 'rolex-6', 'rolex-7', 'rolex-8', 'rolex-9', 'rolex-10', 'rolex-11', 'rolex-12', 'rolex-13', 'rolex-14', 'rolex-15', 'rolex-16', 'rolex-bayan-36-1', 'rolex-bayan-36-2', 'rolex-bayan-36-3', 'rolex-yz-erkek-1', 'rolex-yz-erkek-2', 'rolex-yz-erkek-3', 'rolex-yz-erkek-4', 'rolex-yz-erkek-5', 'rolex-yz-erkek-6', 'rolex-yz-erkek-7', 'rolex-yz-erkek-8', 'rolex-yz-erkek-9', 'rolex-yz-erkek-10', 'rolex-yz-erkek-11', 'rolex-yz-erkek-12', 'rolex-yz-erkek-13', 'rolex-yz-erkek-14', 'rolex-yz-erkek-15', 'rolex-yz-erkek-16', 'rolex-yz-erkek-17', 'rolex-yz-erkek-18', 'rolex-yz-erkek-19', 'rolex-bayan-31-1', 'rolex-bayan-31-2', 'rolex-bayan-31-3', 'rolex-bayan-31-4', 'rolex-bayan-31-5', 'saat-kutulari-1', 'saat-kutulari-2', 'saat-kutulari-3', 'saat-kutulari-4', 'saat-kutulari-5', 'seven-friday-1', 'seven-friday-2', 'seven-friday-3', 'seven-friday-4', 'seven-friday-5', 'seven-friday-6', 'tag-1', 'tag-2', 'tag-3', 'tag-4', 'tag-5', 'tag-6', 'tudor-1', 'tudor-2', 'tudor-3', 'tudor-4', 'tudor-5', 'tudor-6', 'tudor-7', 'tudor-8', 'tudor-9', 'tudor-10', 'ulyse-nardin-1', 'ulyse-nardin-2', 'ulyse-nardin-3', 'ulyse-nardin-4', 'ulyse-nardin-5', 'ulyse-nardin-6', 'ulyse-nardin-7', 'ulyse-nardin-8', 'ulyse-nardin-9', 'ulyse-nardin-10', 'ulyse-nardin-11', 'ulyse-nardin-12', 'ulyse-nardin-13', 'ulyse-nardin-14', 'ulyse-nardin-15', 'ulyse-nardin-16', 'ulyse-nardin-17', 'ulyse-nardin-18', 'ulyse-nardin-19', 'ulyse-nardin-20', 'versace-bayan-1', 'versace-bayan-2', 'versace-bayan-3', 'versace-bayan-4', 'versace-erkek-1', 'versace-erkek-2', 'versace-erkek-3', 'versace-erkek-4', 'versace-erkek-5', 'versace-erkek-6', 'versace-erkek-7', 'versace-erkek-8', 'versace-erkek-9', 'versace-erkek-10', 'washaron-1', 'washaron-2', 'washaron-3', 'washaron-4', 'washaron-5', 'washaron-6', 'washaron-7', 'washaron-8', 'washaron-9', 'washaron-10')
);

insert into product_images (product_id, url, label, sort_order)
select p.id, v.url, v.label, v.sort_order
from (values
  ('ap-erkek-1', '/urunler/ap-erkek/m1-1.jpg', 'Açı 1', 0),
  ('ap-erkek-1', '/urunler/ap-erkek/m1-2.jpg', 'Açı 2', 1),
  ('ap-erkek-2', '/urunler/ap-erkek/m2-1.jpg', 'Açı 1', 0),
  ('ap-erkek-2', '/urunler/ap-erkek/m2-2.jpg', 'Açı 2', 1),
  ('ap-erkek-3', '/urunler/ap-erkek/m3-1.jpg', 'Açı 1', 0),
  ('ap-erkek-3', '/urunler/ap-erkek/m3-2.jpg', 'Açı 2', 1),
  ('ap-erkek-3', '/urunler/ap-erkek/m3-3.jpg', 'Açı 3', 2),
  ('ap-erkek-3', '/urunler/ap-erkek/m3-4.jpg', 'Açı 4', 3),
  ('ap-erkek-4', '/urunler/ap-erkek/m4-1.jpg', 'Açı 1', 0),
  ('ap-erkek-4', '/urunler/ap-erkek/m4-2.jpg', 'Açı 2', 1),
  ('ap-erkek-4', '/urunler/ap-erkek/m4-3.jpg', 'Açı 3', 2),
  ('ap-erkek-4', '/urunler/ap-erkek/m4-4.jpg', 'Açı 4', 3),
  ('ap-erkek-4', '/urunler/ap-erkek/m4-5.jpg', 'Açı 5', 4),
  ('ap-erkek-4', '/urunler/ap-erkek/m4-6.jpg', 'Açı 6', 5),
  ('ap-erkek-5', '/urunler/ap-erkek/m5-1.jpg', 'Açı 1', 0),
  ('ap-erkek-5', '/urunler/ap-erkek/m5-2.jpg', 'Açı 2', 1),
  ('ap-erkek-5', '/urunler/ap-erkek/m5-3.jpg', 'Açı 3', 2),
  ('ap-erkek-5', '/urunler/ap-erkek/m5-4.jpg', 'Açı 4', 3),
  ('ap-erkek-5', '/urunler/ap-erkek/m5-5.jpg', 'Açı 5', 4),
  ('ap-erkek-5', '/urunler/ap-erkek/m5-6.jpg', 'Açı 6', 5),
  ('ap-erkek-6', '/urunler/ap-erkek/m6-1.jpg', 'Açı 1', 0),
  ('ap-bayan-1', '/urunler/ap-bayan/m1-1.jpg', 'Açı 1', 0),
  ('ap-bayan-1', '/urunler/ap-bayan/m1-2.jpg', 'Açı 2', 1),
  ('ap-bayan-1', '/urunler/ap-bayan/m1-3.jpg', 'Açı 3', 2),
  ('ap-bayan-1', '/urunler/ap-bayan/m1-4.jpg', 'Açı 4', 3),
  ('ap-bayan-2', '/urunler/ap-bayan/m2-1.jpg', 'Açı 1', 0),
  ('ap-bayan-3', '/urunler/ap-bayan/m3-1.jpg', 'Açı 1', 0),
  ('ap-bayan-3', '/urunler/ap-bayan/m3-2.jpg', 'Açı 2', 1),
  ('ap-bayan-3', '/urunler/ap-bayan/m3-3.jpg', 'Açı 3', 2),
  ('ap-bayan-3', '/urunler/ap-bayan/m3-4.jpg', 'Açı 4', 3),
  ('ap-bayan-3', '/urunler/ap-bayan/m3-5.jpg', 'Açı 5', 4),
  ('ap-bayan-3', '/urunler/ap-bayan/m3-6.jpg', 'Açı 6', 5),
  ('ap-bayan-3', '/urunler/ap-bayan/m3-7.jpg', 'Açı 7', 6),
  ('ap-bayan-3', '/urunler/ap-bayan/m3-8.jpg', 'Açı 8', 7),
  ('ap-bayan-4', '/urunler/ap-bayan/m4-1.jpg', 'Açı 1', 0),
  ('ap-bayan-4', '/urunler/ap-bayan/m4-2.jpg', 'Açı 2', 1),
  ('ap-bayan-4', '/urunler/ap-bayan/m4-3.jpg', 'Açı 3', 2),
  ('ap-bayan-4', '/urunler/ap-bayan/m4-4.jpg', 'Açı 4', 3),
  ('ap-bayan-4', '/urunler/ap-bayan/m4-5.jpg', 'Açı 5', 4),
  ('ap-bayan-4', '/urunler/ap-bayan/m4-6.jpg', 'Açı 6', 5),
  ('ap-bayan-4', '/urunler/ap-bayan/m4-7.jpg', 'Açı 7', 6),
  ('ap-bayan-4', '/urunler/ap-bayan/m4-8.jpg', 'Açı 8', 7),
  ('ap-bayan-4', '/urunler/ap-bayan/m4-9.jpg', 'Açı 9', 8),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-1.jpg', 'Açı 1', 0),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-2.jpg', 'Açı 2', 1),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-3.jpg', 'Açı 3', 2),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-4.jpg', 'Açı 4', 3),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-5.jpg', 'Açı 5', 4),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-6.jpg', 'Açı 6', 5),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-7.jpg', 'Açı 7', 6),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-8.jpg', 'Açı 8', 7),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-9.jpg', 'Açı 9', 8),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-10.jpg', 'Açı 10', 9),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-11.jpg', 'Açı 11', 10),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-12.jpg', 'Açı 12', 11),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-13.jpg', 'Açı 13', 12),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-14.jpg', 'Açı 14', 13),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-15.jpg', 'Açı 15', 14),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-16.jpg', 'Açı 16', 15),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-17.jpg', 'Açı 17', 16),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-18.jpg', 'Açı 18', 17),
  ('bulgari-bayan-1', '/urunler/bulgari-bayan/m1-19.jpg', 'Açı 19', 18),
  ('bulgari-bayan-2', '/urunler/bulgari-bayan/m2-1.jpg', 'Açı 1', 0),
  ('bulgari-bayan-2', '/urunler/bulgari-bayan/m2-2.jpg', 'Açı 2', 1),
  ('bulgari-bayan-2', '/urunler/bulgari-bayan/m2-3.jpg', 'Açı 3', 2),
  ('bulgari-bayan-2', '/urunler/bulgari-bayan/m2-4.jpg', 'Açı 4', 3),
  ('bulgari-bayan-2', '/urunler/bulgari-bayan/m2-5.jpg', 'Açı 5', 4),
  ('bulgari-bayan-2', '/urunler/bulgari-bayan/m2-6.jpg', 'Açı 6', 5),
  ('bulgari-bayan-2', '/urunler/bulgari-bayan/m2-7.jpg', 'Açı 7', 6),
  ('bulgari-bayan-2', '/urunler/bulgari-bayan/m2-8.jpg', 'Açı 8', 7),
  ('bulgari-bayan-2', '/urunler/bulgari-bayan/m2-9.jpg', 'Açı 9', 8),
  ('bulgari-bayan-2', '/urunler/bulgari-bayan/m2-10.jpg', 'Açı 10', 9),
  ('bulgari-bayan-3', '/urunler/bulgari-bayan/m3-1.jpg', 'Açı 1', 0),
  ('bulgari-bayan-3', '/urunler/bulgari-bayan/m3-2.jpg', 'Açı 2', 1),
  ('bulgari-bayan-3', '/urunler/bulgari-bayan/m3-3.jpg', 'Açı 3', 2),
  ('bulgari-bayan-3', '/urunler/bulgari-bayan/m3-4.jpg', 'Açı 4', 3),
  ('bulgari-bayan-3', '/urunler/bulgari-bayan/m3-5.jpg', 'Açı 5', 4),
  ('bulgari-bayan-3', '/urunler/bulgari-bayan/m3-6.jpg', 'Açı 6', 5),
  ('bulgari-bayan-3', '/urunler/bulgari-bayan/m3-7.jpg', 'Açı 7', 6),
  ('bulgari-bayan-3', '/urunler/bulgari-bayan/m3-8.jpg', 'Açı 8', 7),
  ('bulgari-bayan-3', '/urunler/bulgari-bayan/m3-9.jpg', 'Açı 9', 8),
  ('bulgari-bayan-4', '/urunler/bulgari-bayan/m4-1.jpg', 'Açı 1', 0),
  ('cartier-erkek-1', '/urunler/cartier-erkek/m1-1.jpg', 'Açı 1', 0),
  ('cartier-erkek-2', '/urunler/cartier-erkek/m2-1.jpg', 'Açı 1', 0),
  ('cartier-erkek-2', '/urunler/cartier-erkek/m2-2.jpg', 'Açı 2', 1),
  ('cartier-erkek-3', '/urunler/cartier-erkek/m3-1.jpg', 'Açı 1', 0),
  ('cartier-erkek-3', '/urunler/cartier-erkek/m3-2.jpg', 'Açı 2', 1),
  ('cartier-erkek-4', '/urunler/cartier-erkek/m4-1.jpg', 'Açı 1', 0),
  ('cartier-erkek-4', '/urunler/cartier-erkek/m4-2.jpg', 'Açı 2', 1),
  ('cartier-erkek-5', '/urunler/cartier-erkek/m5-1.jpg', 'Açı 1', 0),
  ('cartier-erkek-6', '/urunler/cartier-erkek/m6-1.jpg', 'Açı 1', 0),
  ('cartier-erkek-7', '/urunler/cartier-erkek/m7-1.jpg', 'Açı 1', 0),
  ('cartier-erkek-7', '/urunler/cartier-erkek/m7-2.jpg', 'Açı 2', 1),
  ('cartier-erkek-7', '/urunler/cartier-erkek/m7-3.jpg', 'Açı 3', 2),
  ('cartier-erkek-7', '/urunler/cartier-erkek/m7-4.jpg', 'Açı 4', 3),
  ('cartier-erkek-7', '/urunler/cartier-erkek/m7-5.jpg', 'Açı 5', 4),
  ('cartier-erkek-7', '/urunler/cartier-erkek/m7-6.jpg', 'Açı 6', 5),
  ('cartier-erkek-8', '/urunler/cartier-erkek/m8-1.jpg', 'Açı 1', 0),
  ('cartier-erkek-8', '/urunler/cartier-erkek/m8-2.jpg', 'Açı 2', 1),
  ('cartier-erkek-8', '/urunler/cartier-erkek/m8-3.jpg', 'Açı 3', 2),
  ('cartier-erkek-9', '/urunler/cartier-erkek/m9-1.jpg', 'Açı 1', 0),
  ('cartier-erkek-10', '/urunler/cartier-erkek/m10-1.jpg', 'Açı 1', 0),
  ('cartier-erkek-11', '/urunler/cartier-erkek/m11-1.jpg', 'Açı 1', 0),
  ('cartier-erkek-12', '/urunler/cartier-erkek/m12-1.jpg', 'Açı 1', 0),
  ('cartier-bayan-1', '/urunler/cartier-bayan/m1-1.jpg', 'Açı 1', 0),
  ('cartier-bayan-1', '/urunler/cartier-bayan/m1-2.jpg', 'Açı 2', 1),
  ('cartier-bayan-1', '/urunler/cartier-bayan/m1-3.jpg', 'Açı 3', 2),
  ('cartier-bayan-1', '/urunler/cartier-bayan/m1-4.jpg', 'Açı 4', 3),
  ('cartier-bayan-2', '/urunler/cartier-bayan/m2-1.jpg', 'Açı 1', 0),
  ('cartier-bayan-2', '/urunler/cartier-bayan/m2-2.jpg', 'Açı 2', 1),
  ('cartier-bayan-2', '/urunler/cartier-bayan/m2-3.jpg', 'Açı 3', 2),
  ('cartier-bayan-2', '/urunler/cartier-bayan/m2-4.jpg', 'Açı 4', 3),
  ('cartier-bayan-2', '/urunler/cartier-bayan/m2-5.jpg', 'Açı 5', 4),
  ('cartier-bayan-2', '/urunler/cartier-bayan/m2-6.jpg', 'Açı 6', 5),
  ('cartier-bayan-3', '/urunler/cartier-bayan/m3-1.jpg', 'Açı 1', 0),
  ('cartier-bayan-4', '/urunler/cartier-bayan/m4-1.jpg', 'Açı 1', 0),
  ('cartier-bayan-5', '/urunler/cartier-bayan/m5-1.jpg', 'Açı 1', 0),
  ('cartier-bayan-6', '/urunler/cartier-bayan/m6-1.jpg', 'Açı 1', 0),
  ('cartier-bayan-6', '/urunler/cartier-bayan/m6-2.jpg', 'Açı 2', 1),
  ('cartier-bayan-7', '/urunler/cartier-bayan/m7-1.jpg', 'Açı 1', 0),
  ('cartier-bayan-7', '/urunler/cartier-bayan/m7-2.jpg', 'Açı 2', 1),
  ('cartier-bayan-8', '/urunler/cartier-bayan/m8-1.jpg', 'Açı 1', 0),
  ('cartier-bayan-9', '/urunler/cartier-bayan/m9-1.jpg', 'Açı 1', 0),
  ('cartier-bayan-9', '/urunler/cartier-bayan/m9-2.jpg', 'Açı 2', 1),
  ('cartier-bayan-9', '/urunler/cartier-bayan/m9-3.jpg', 'Açı 3', 2),
  ('cartier-bayan-9', '/urunler/cartier-bayan/m9-4.jpg', 'Açı 4', 3),
  ('cartier-bayan-9', '/urunler/cartier-bayan/m9-5.jpg', 'Açı 5', 4),
  ('cartier-bayan-9', '/urunler/cartier-bayan/m9-6.jpg', 'Açı 6', 5),
  ('cartier-bayan-9', '/urunler/cartier-bayan/m9-7.jpg', 'Açı 7', 6),
  ('cartier-bayan-9', '/urunler/cartier-bayan/m9-8.jpg', 'Açı 8', 7),
  ('cartier-bayan-10', '/urunler/cartier-bayan/m10-1.jpg', 'Açı 1', 0),
  ('cartier-bayan-10', '/urunler/cartier-bayan/m10-2.jpg', 'Açı 2', 1),
  ('cartier-bayan-10', '/urunler/cartier-bayan/m10-3.jpg', 'Açı 3', 2),
  ('cartier-bayan-11', '/urunler/cartier-bayan/m11-1.jpg', 'Açı 1', 0),
  ('cartier-bayan-12', '/urunler/cartier-bayan/m12-1.jpg', 'Açı 1', 0),
  ('cartier-bayan-12', '/urunler/cartier-bayan/m12-2.jpg', 'Açı 2', 1),
  ('cartier-bayan-12', '/urunler/cartier-bayan/m12-3.jpg', 'Açı 3', 2),
  ('cartier-bayan-12', '/urunler/cartier-bayan/m12-4.jpg', 'Açı 4', 3),
  ('cartier-bayan-13', '/urunler/cartier-bayan/m13-1.jpg', 'Açı 1', 0),
  ('cartier-bayan-13', '/urunler/cartier-bayan/m13-2.jpg', 'Açı 2', 1),
  ('cartier-bayan-13', '/urunler/cartier-bayan/m13-3.jpg', 'Açı 3', 2),
  ('cartier-bayan-13', '/urunler/cartier-bayan/m13-4.jpg', 'Açı 4', 3),
  ('cartier-bayan-14', '/urunler/cartier-bayan/m14-1.jpg', 'Açı 1', 0),
  ('cartier-bayan-15', '/urunler/cartier-bayan/m15-1.jpg', 'Açı 1', 0),
  ('cartier-bayan-16', '/urunler/cartier-bayan/m16-1.jpg', 'Açı 1', 0),
  ('cartier-bayan-17', '/urunler/cartier-bayan/m17-1.jpg', 'Açı 1', 0),
  ('citizen-1', '/urunler/citizen/m1-1.jpg', 'Açı 1', 0),
  ('citizen-2', '/urunler/citizen/m2-1.jpg', 'Açı 1', 0),
  ('eta-rolex-1', '/urunler/eta-rolex/m1-1.jpg', 'Açı 1', 0),
  ('eta-rolex-1', '/urunler/eta-rolex/m1-2.jpg', 'Açı 2', 1),
  ('eta-rolex-1', '/urunler/eta-rolex/m1-3.jpg', 'Açı 3', 2),
  ('eta-rolex-1', '/urunler/eta-rolex/m1-4.jpg', 'Açı 4', 3),
  ('frank-muller-1', '/urunler/frank-muller/m1-1.jpg', 'Açı 1', 0),
  ('frank-muller-2', '/urunler/frank-muller/m2-1.jpg', 'Açı 1', 0),
  ('frank-muller-3', '/urunler/frank-muller/m3-1.jpg', 'Açı 1', 0),
  ('frank-muller-4', '/urunler/frank-muller/m4-1.jpg', 'Açı 1', 0),
  ('frank-muller-5', '/urunler/frank-muller/m5-1.jpg', 'Açı 1', 0),
  ('frank-muller-6', '/urunler/frank-muller/m6-1.jpg', 'Açı 1', 0),
  ('frank-muller-7', '/urunler/frank-muller/m7-1.jpg', 'Açı 1', 0),
  ('frank-muller-8', '/urunler/frank-muller/m8-1.jpg', 'Açı 1', 0),
  ('frank-muller-9', '/urunler/frank-muller/m9-1.jpg', 'Açı 1', 0),
  ('frank-muller-10', '/urunler/frank-muller/m10-1.jpg', 'Açı 1', 0),
  ('frank-muller-11', '/urunler/frank-muller/m11-1.jpg', 'Açı 1', 0),
  ('frank-muller-12', '/urunler/frank-muller/m12-1.jpg', 'Açı 1', 0),
  ('frank-muller-13', '/urunler/frank-muller/m13-1.jpg', 'Açı 1', 0),
  ('frank-muller-14', '/urunler/frank-muller/m14-1.jpg', 'Açı 1', 0),
  ('frank-muller-15', '/urunler/frank-muller/m15-1.jpg', 'Açı 1', 0),
  ('gc-erkek-1', '/urunler/gc-erkek/m1-1.jpg', 'Açı 1', 0),
  ('gc-erkek-1', '/urunler/gc-erkek/m1-2.jpg', 'Açı 2', 1),
  ('gc-erkek-1', '/urunler/gc-erkek/m1-3.jpg', 'Açı 3', 2),
  ('invicta-1', '/urunler/invicta/m1-1.jpg', 'Açı 1', 0),
  ('invicta-2', '/urunler/invicta/m2-1.jpg', 'Açı 1', 0),
  ('invicta-3', '/urunler/invicta/m3-1.jpg', 'Açı 1', 0),
  ('jaeger-1', '/urunler/jaeger/m1-1.jpg', 'Açı 1', 0),
  ('jaeger-1', '/urunler/jaeger/m1-2.jpg', 'Açı 2', 1),
  ('jaeger-1', '/urunler/jaeger/m1-3.jpg', 'Açı 3', 2),
  ('jaeger-2', '/urunler/jaeger/m2-1.jpg', 'Açı 1', 0),
  ('jaeger-2', '/urunler/jaeger/m2-2.jpg', 'Açı 2', 1),
  ('jaeger-2', '/urunler/jaeger/m2-3.jpg', 'Açı 3', 2),
  ('jaeger-2', '/urunler/jaeger/m2-4.jpg', 'Açı 4', 3),
  ('longin-1', '/urunler/longin/m1-1.jpg', 'Açı 1', 0),
  ('longin-2', '/urunler/longin/m2-1.jpg', 'Açı 1', 0),
  ('longin-2', '/urunler/longin/m2-2.jpg', 'Açı 2', 1),
  ('longin-2', '/urunler/longin/m2-3.jpg', 'Açı 3', 2),
  ('longin-2', '/urunler/longin/m2-4.jpg', 'Açı 4', 3),
  ('longin-2', '/urunler/longin/m2-5.jpg', 'Açı 5', 4),
  ('longin-2', '/urunler/longin/m2-6.jpg', 'Açı 6', 5),
  ('longin-3', '/urunler/longin/m3-1.jpg', 'Açı 1', 0),
  ('longin-4', '/urunler/longin/m4-1.jpg', 'Açı 1', 0),
  ('longin-4', '/urunler/longin/m4-2.jpg', 'Açı 2', 1),
  ('longin-5', '/urunler/longin/m5-1.jpg', 'Açı 1', 0),
  ('longin-6', '/urunler/longin/m6-1.jpg', 'Açı 1', 0),
  ('longin-7', '/urunler/longin/m7-1.jpg', 'Açı 1', 0),
  ('longin-8', '/urunler/longin/m8-1.jpg', 'Açı 1', 0),
  ('longin-9', '/urunler/longin/m9-1.jpg', 'Açı 1', 0),
  ('longin-10', '/urunler/longin/m10-1.jpg', 'Açı 1', 0),
  ('oris-1', '/urunler/oris/m1-1.jpg', 'Açı 1', 0),
  ('oris-1', '/urunler/oris/m1-2.jpg', 'Açı 2', 1),
  ('patek-1', '/urunler/patek/m1-1.jpg', 'Açı 1', 0),
  ('patek-1', '/urunler/patek/m1-2.jpg', 'Açı 2', 1),
  ('patek-1', '/urunler/patek/m1-3.jpg', 'Açı 3', 2),
  ('patek-1', '/urunler/patek/m1-4.jpg', 'Açı 4', 3),
  ('patek-1', '/urunler/patek/m1-5.jpg', 'Açı 5', 4),
  ('patek-1', '/urunler/patek/m1-6.jpg', 'Açı 6', 5),
  ('patek-1', '/urunler/patek/m1-7.jpg', 'Açı 7', 6),
  ('patek-1', '/urunler/patek/m1-8.jpg', 'Açı 8', 7),
  ('patek-1', '/urunler/patek/m1-9.jpg', 'Açı 9', 8),
  ('patek-1', '/urunler/patek/m1-10.jpg', 'Açı 10', 9),
  ('patek-1', '/urunler/patek/m1-11.jpg', 'Açı 11', 10),
  ('patek-2', '/urunler/patek/m2-1.jpg', 'Açı 1', 0),
  ('patek-2', '/urunler/patek/m2-2.jpg', 'Açı 2', 1),
  ('patek-2', '/urunler/patek/m2-3.jpg', 'Açı 3', 2),
  ('patek-2', '/urunler/patek/m2-4.jpg', 'Açı 4', 3),
  ('patek-2', '/urunler/patek/m2-5.jpg', 'Açı 5', 4),
  ('patek-2', '/urunler/patek/m2-6.jpg', 'Açı 6', 5),
  ('patek-2', '/urunler/patek/m2-7.jpg', 'Açı 7', 6),
  ('patek-2', '/urunler/patek/m2-8.jpg', 'Açı 8', 7),
  ('patek-2', '/urunler/patek/m2-9.jpg', 'Açı 9', 8),
  ('patek-2', '/urunler/patek/m2-10.jpg', 'Açı 10', 9),
  ('patek-2', '/urunler/patek/m2-11.jpg', 'Açı 11', 10),
  ('patek-2', '/urunler/patek/m2-12.jpg', 'Açı 12', 11),
  ('patek-2', '/urunler/patek/m2-13.jpg', 'Açı 13', 12),
  ('patek-2', '/urunler/patek/m2-14.jpg', 'Açı 14', 13),
  ('patek-2', '/urunler/patek/m2-15.jpg', 'Açı 15', 14),
  ('patek-2', '/urunler/patek/m2-16.jpg', 'Açı 16', 15),
  ('patek-2', '/urunler/patek/m2-17.jpg', 'Açı 17', 16),
  ('patek-3', '/urunler/patek/m3-1.jpg', 'Açı 1', 0),
  ('patek-3', '/urunler/patek/m3-2.jpg', 'Açı 2', 1),
  ('patek-4', '/urunler/patek/m4-1.jpg', 'Açı 1', 0),
  ('patek-4', '/urunler/patek/m4-2.jpg', 'Açı 2', 1),
  ('patek-5', '/urunler/patek/m5-1.jpg', 'Açı 1', 0),
  ('patek-6', '/urunler/patek/m6-1.jpg', 'Açı 1', 0),
  ('patek-6', '/urunler/patek/m6-2.jpg', 'Açı 2', 1),
  ('patek-klasik-1', '/urunler/patek-klasik/m1-1.jpg', 'Açı 1', 0),
  ('patek-klasik-2', '/urunler/patek-klasik/m2-1.jpg', 'Açı 1', 0),
  ('patek-klasik-3', '/urunler/patek-klasik/m3-1.jpg', 'Açı 1', 0),
  ('patek-klasik-4', '/urunler/patek-klasik/m4-1.jpg', 'Açı 1', 0),
  ('patek-bayan-1', '/urunler/patek-bayan/m1-1.jpg', 'Açı 1', 0),
  ('patek-bayan-2', '/urunler/patek-bayan/m2-1.jpg', 'Açı 1', 0),
  ('patek-bayan-2', '/urunler/patek-bayan/m2-2.jpg', 'Açı 2', 1),
  ('patek-bayan-2', '/urunler/patek-bayan/m2-3.jpg', 'Açı 3', 2),
  ('patek-bayan-2', '/urunler/patek-bayan/m2-4.jpg', 'Açı 4', 3),
  ('patek-bayan-2', '/urunler/patek-bayan/m2-5.jpg', 'Açı 5', 4),
  ('patek-bayan-2', '/urunler/patek-bayan/m2-6.jpg', 'Açı 6', 5),
  ('patek-bayan-2', '/urunler/patek-bayan/m2-7.jpg', 'Açı 7', 6),
  ('patek-bayan-2', '/urunler/patek-bayan/m2-8.jpg', 'Açı 8', 7),
  ('patek-bayan-2', '/urunler/patek-bayan/m2-9.jpg', 'Açı 9', 8),
  ('patek-bayan-2', '/urunler/patek-bayan/m2-10.jpg', 'Açı 10', 9),
  ('patek-bayan-3', '/urunler/patek-bayan/m3-1.jpg', 'Açı 1', 0),
  ('patek-bayan-3', '/urunler/patek-bayan/m3-2.jpg', 'Açı 2', 1),
  ('patek-bayan-3', '/urunler/patek-bayan/m3-3.jpg', 'Açı 3', 2),
  ('patek-bayan-3', '/urunler/patek-bayan/m3-4.jpg', 'Açı 4', 3),
  ('patek-ince-kasa-ppf-1', '/urunler/patek-ince-kasa-ppf/m1-1.jpg', 'Açı 1', 0),
  ('patek-ince-kasa-ppf-1', '/urunler/patek-ince-kasa-ppf/m1-2.jpg', 'Açı 2', 1),
  ('patek-ince-kasa-ppf-1', '/urunler/patek-ince-kasa-ppf/m1-3.jpg', 'Açı 3', 2),
  ('patek-ince-kasa-ppf-1', '/urunler/patek-ince-kasa-ppf/m1-4.jpg', 'Açı 4', 3),
  ('patek-ince-kasa-ppf-1', '/urunler/patek-ince-kasa-ppf/m1-5.jpg', 'Açı 5', 4),
  ('patek-ince-kasa-ppf-1', '/urunler/patek-ince-kasa-ppf/m1-6.jpg', 'Açı 6', 5),
  ('rado-1', '/urunler/rado/m1-1.jpg', 'Açı 1', 0),
  ('richard-mille-1', '/urunler/richard-mille/m1-1.jpg', 'Açı 1', 0),
  ('richard-mille-2', '/urunler/richard-mille/m2-1.jpg', 'Açı 1', 0),
  ('richard-mille-3', '/urunler/richard-mille/m3-1.jpg', 'Açı 1', 0),
  ('rolex-1', '/urunler/rolex/m1-1.jpg', 'Açı 1', 0),
  ('rolex-2', '/urunler/rolex/m2-1.jpg', 'Açı 1', 0),
  ('rolex-3', '/urunler/rolex/m3-1.jpg', 'Açı 1', 0),
  ('rolex-3', '/urunler/rolex/m3-2.jpg', 'Açı 2', 1),
  ('rolex-4', '/urunler/rolex/m4-1.jpg', 'Açı 1', 0),
  ('rolex-4', '/urunler/rolex/m4-2.jpg', 'Açı 2', 1),
  ('rolex-5', '/urunler/rolex/m5-1.jpg', 'Açı 1', 0),
  ('rolex-6', '/urunler/rolex/m6-1.jpg', 'Açı 1', 0),
  ('rolex-6', '/urunler/rolex/m6-2.jpg', 'Açı 2', 1),
  ('rolex-7', '/urunler/rolex/m7-1.jpg', 'Açı 1', 0),
  ('rolex-7', '/urunler/rolex/m7-2.jpg', 'Açı 2', 1),
  ('rolex-7', '/urunler/rolex/m7-3.jpg', 'Açı 3', 2),
  ('rolex-7', '/urunler/rolex/m7-4.jpg', 'Açı 4', 3),
  ('rolex-7', '/urunler/rolex/m7-5.jpg', 'Açı 5', 4),
  ('rolex-7', '/urunler/rolex/m7-6.jpg', 'Açı 6', 5),
  ('rolex-7', '/urunler/rolex/m7-7.jpg', 'Açı 7', 6),
  ('rolex-7', '/urunler/rolex/m7-8.jpg', 'Açı 8', 7),
  ('rolex-7', '/urunler/rolex/m7-9.jpg', 'Açı 9', 8),
  ('rolex-7', '/urunler/rolex/m7-10.jpg', 'Açı 10', 9),
  ('rolex-7', '/urunler/rolex/m7-11.jpg', 'Açı 11', 10),
  ('rolex-7', '/urunler/rolex/m7-12.jpg', 'Açı 12', 11),
  ('rolex-7', '/urunler/rolex/m7-13.jpg', 'Açı 13', 12),
  ('rolex-7', '/urunler/rolex/m7-14.jpg', 'Açı 14', 13),
  ('rolex-8', '/urunler/rolex/m8-1.jpg', 'Açı 1', 0),
  ('rolex-8', '/urunler/rolex/m8-2.jpg', 'Açı 2', 1),
  ('rolex-9', '/urunler/rolex/m9-1.jpg', 'Açı 1', 0),
  ('rolex-9', '/urunler/rolex/m9-2.jpg', 'Açı 2', 1),
  ('rolex-9', '/urunler/rolex/m9-3.jpg', 'Açı 3', 2),
  ('rolex-9', '/urunler/rolex/m9-4.jpg', 'Açı 4', 3),
  ('rolex-9', '/urunler/rolex/m9-5.jpg', 'Açı 5', 4),
  ('rolex-9', '/urunler/rolex/m9-6.jpg', 'Açı 6', 5),
  ('rolex-9', '/urunler/rolex/m9-7.jpg', 'Açı 7', 6),
  ('rolex-9', '/urunler/rolex/m9-8.jpg', 'Açı 8', 7),
  ('rolex-9', '/urunler/rolex/m9-9.jpg', 'Açı 9', 8),
  ('rolex-9', '/urunler/rolex/m9-10.jpg', 'Açı 10', 9),
  ('rolex-9', '/urunler/rolex/m9-11.jpg', 'Açı 11', 10),
  ('rolex-9', '/urunler/rolex/m9-12.jpg', 'Açı 12', 11),
  ('rolex-9', '/urunler/rolex/m9-13.jpg', 'Açı 13', 12),
  ('rolex-9', '/urunler/rolex/m9-14.jpg', 'Açı 14', 13),
  ('rolex-10', '/urunler/rolex/m10-1.jpg', 'Açı 1', 0),
  ('rolex-11', '/urunler/rolex/m11-1.jpg', 'Açı 1', 0),
  ('rolex-11', '/urunler/rolex/m11-2.jpg', 'Açı 2', 1),
  ('rolex-11', '/urunler/rolex/m11-3.jpg', 'Açı 3', 2),
  ('rolex-11', '/urunler/rolex/m11-4.jpg', 'Açı 4', 3),
  ('rolex-11', '/urunler/rolex/m11-5.jpg', 'Açı 5', 4),
  ('rolex-11', '/urunler/rolex/m11-6.jpg', 'Açı 6', 5),
  ('rolex-11', '/urunler/rolex/m11-7.jpg', 'Açı 7', 6),
  ('rolex-11', '/urunler/rolex/m11-8.jpg', 'Açı 8', 7),
  ('rolex-11', '/urunler/rolex/m11-9.jpg', 'Açı 9', 8),
  ('rolex-11', '/urunler/rolex/m11-10.jpg', 'Açı 10', 9),
  ('rolex-11', '/urunler/rolex/m11-11.jpg', 'Açı 11', 10),
  ('rolex-11', '/urunler/rolex/m11-12.jpg', 'Açı 12', 11),
  ('rolex-11', '/urunler/rolex/m11-13.jpg', 'Açı 13', 12),
  ('rolex-11', '/urunler/rolex/m11-14.jpg', 'Açı 14', 13),
  ('rolex-12', '/urunler/rolex/m12-1.jpg', 'Açı 1', 0),
  ('rolex-12', '/urunler/rolex/m12-2.jpg', 'Açı 2', 1),
  ('rolex-12', '/urunler/rolex/m12-3.jpg', 'Açı 3', 2),
  ('rolex-13', '/urunler/rolex/m13-1.jpg', 'Açı 1', 0),
  ('rolex-14', '/urunler/rolex/m14-1.jpg', 'Açı 1', 0),
  ('rolex-15', '/urunler/rolex/m15-1.jpg', 'Açı 1', 0),
  ('rolex-16', '/urunler/rolex/m16-1.jpg', 'Açı 1', 0),
  ('rolex-bayan-36-1', '/urunler/rolex-bayan-36/m1-1.jpg', 'Açı 1', 0),
  ('rolex-bayan-36-1', '/urunler/rolex-bayan-36/m1-2.jpg', 'Açı 2', 1),
  ('rolex-bayan-36-1', '/urunler/rolex-bayan-36/m1-3.jpg', 'Açı 3', 2),
  ('rolex-bayan-36-1', '/urunler/rolex-bayan-36/m1-4.jpg', 'Açı 4', 3),
  ('rolex-bayan-36-1', '/urunler/rolex-bayan-36/m1-5.jpg', 'Açı 5', 4),
  ('rolex-bayan-36-1', '/urunler/rolex-bayan-36/m1-6.jpg', 'Açı 6', 5),
  ('rolex-bayan-36-2', '/urunler/rolex-bayan-36/m2-1.jpg', 'Açı 1', 0),
  ('rolex-bayan-36-2', '/urunler/rolex-bayan-36/m2-2.jpg', 'Açı 2', 1),
  ('rolex-bayan-36-2', '/urunler/rolex-bayan-36/m2-3.jpg', 'Açı 3', 2),
  ('rolex-bayan-36-2', '/urunler/rolex-bayan-36/m2-4.jpg', 'Açı 4', 3),
  ('rolex-bayan-36-3', '/urunler/rolex-bayan-36/m3-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-1', '/urunler/rolex-yz-erkek/m1-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-1', '/urunler/rolex-yz-erkek/m1-2.jpg', 'Açı 2', 1),
  ('rolex-yz-erkek-2', '/urunler/rolex-yz-erkek/m2-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-2', '/urunler/rolex-yz-erkek/m2-2.jpg', 'Açı 2', 1),
  ('rolex-yz-erkek-2', '/urunler/rolex-yz-erkek/m2-3.jpg', 'Açı 3', 2),
  ('rolex-yz-erkek-2', '/urunler/rolex-yz-erkek/m2-4.jpg', 'Açı 4', 3),
  ('rolex-yz-erkek-2', '/urunler/rolex-yz-erkek/m2-5.jpg', 'Açı 5', 4),
  ('rolex-yz-erkek-3', '/urunler/rolex-yz-erkek/m3-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-4', '/urunler/rolex-yz-erkek/m4-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-4', '/urunler/rolex-yz-erkek/m4-2.jpg', 'Açı 2', 1),
  ('rolex-yz-erkek-4', '/urunler/rolex-yz-erkek/m4-3.jpg', 'Açı 3', 2),
  ('rolex-yz-erkek-5', '/urunler/rolex-yz-erkek/m5-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-6', '/urunler/rolex-yz-erkek/m6-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-6', '/urunler/rolex-yz-erkek/m6-2.jpg', 'Açı 2', 1),
  ('rolex-yz-erkek-7', '/urunler/rolex-yz-erkek/m7-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-7', '/urunler/rolex-yz-erkek/m7-2.jpg', 'Açı 2', 1),
  ('rolex-yz-erkek-7', '/urunler/rolex-yz-erkek/m7-3.jpg', 'Açı 3', 2),
  ('rolex-yz-erkek-7', '/urunler/rolex-yz-erkek/m7-4.jpg', 'Açı 4', 3),
  ('rolex-yz-erkek-7', '/urunler/rolex-yz-erkek/m7-5.jpg', 'Açı 5', 4),
  ('rolex-yz-erkek-7', '/urunler/rolex-yz-erkek/m7-6.jpg', 'Açı 6', 5),
  ('rolex-yz-erkek-7', '/urunler/rolex-yz-erkek/m7-7.jpg', 'Açı 7', 6),
  ('rolex-yz-erkek-7', '/urunler/rolex-yz-erkek/m7-8.jpg', 'Açı 8', 7),
  ('rolex-yz-erkek-7', '/urunler/rolex-yz-erkek/m7-9.jpg', 'Açı 9', 8),
  ('rolex-yz-erkek-7', '/urunler/rolex-yz-erkek/m7-10.jpg', 'Açı 10', 9),
  ('rolex-yz-erkek-7', '/urunler/rolex-yz-erkek/m7-11.jpg', 'Açı 11', 10),
  ('rolex-yz-erkek-7', '/urunler/rolex-yz-erkek/m7-12.jpg', 'Açı 12', 11),
  ('rolex-yz-erkek-7', '/urunler/rolex-yz-erkek/m7-13.jpg', 'Açı 13', 12),
  ('rolex-yz-erkek-7', '/urunler/rolex-yz-erkek/m7-14.jpg', 'Açı 14', 13),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-2.jpg', 'Açı 2', 1),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-3.jpg', 'Açı 3', 2),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-4.jpg', 'Açı 4', 3),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-5.jpg', 'Açı 5', 4),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-6.jpg', 'Açı 6', 5),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-7.jpg', 'Açı 7', 6),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-8.jpg', 'Açı 8', 7),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-9.jpg', 'Açı 9', 8),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-10.jpg', 'Açı 10', 9),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-11.jpg', 'Açı 11', 10),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-12.jpg', 'Açı 12', 11),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-13.jpg', 'Açı 13', 12),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-14.jpg', 'Açı 14', 13),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-15.jpg', 'Açı 15', 14),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-16.jpg', 'Açı 16', 15),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-17.jpg', 'Açı 17', 16),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-18.jpg', 'Açı 18', 17),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-19.jpg', 'Açı 19', 18),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-20.jpg', 'Açı 20', 19),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-21.jpg', 'Açı 21', 20),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-22.jpg', 'Açı 22', 21),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-23.jpg', 'Açı 23', 22),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-24.jpg', 'Açı 24', 23),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-25.jpg', 'Açı 25', 24),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-26.jpg', 'Açı 26', 25),
  ('rolex-yz-erkek-8', '/urunler/rolex-yz-erkek/m8-27.jpg', 'Açı 27', 26),
  ('rolex-yz-erkek-9', '/urunler/rolex-yz-erkek/m9-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-9', '/urunler/rolex-yz-erkek/m9-2.jpg', 'Açı 2', 1),
  ('rolex-yz-erkek-10', '/urunler/rolex-yz-erkek/m10-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-11', '/urunler/rolex-yz-erkek/m11-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-11', '/urunler/rolex-yz-erkek/m11-2.jpg', 'Açı 2', 1),
  ('rolex-yz-erkek-11', '/urunler/rolex-yz-erkek/m11-3.jpg', 'Açı 3', 2),
  ('rolex-yz-erkek-11', '/urunler/rolex-yz-erkek/m11-4.jpg', 'Açı 4', 3),
  ('rolex-yz-erkek-11', '/urunler/rolex-yz-erkek/m11-5.jpg', 'Açı 5', 4),
  ('rolex-yz-erkek-11', '/urunler/rolex-yz-erkek/m11-6.jpg', 'Açı 6', 5),
  ('rolex-yz-erkek-12', '/urunler/rolex-yz-erkek/m12-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-12', '/urunler/rolex-yz-erkek/m12-2.jpg', 'Açı 2', 1),
  ('rolex-yz-erkek-13', '/urunler/rolex-yz-erkek/m13-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-14', '/urunler/rolex-yz-erkek/m14-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-14', '/urunler/rolex-yz-erkek/m14-2.jpg', 'Açı 2', 1),
  ('rolex-yz-erkek-14', '/urunler/rolex-yz-erkek/m14-3.jpg', 'Açı 3', 2),
  ('rolex-yz-erkek-14', '/urunler/rolex-yz-erkek/m14-4.jpg', 'Açı 4', 3),
  ('rolex-yz-erkek-14', '/urunler/rolex-yz-erkek/m14-5.jpg', 'Açı 5', 4),
  ('rolex-yz-erkek-14', '/urunler/rolex-yz-erkek/m14-6.jpg', 'Açı 6', 5),
  ('rolex-yz-erkek-14', '/urunler/rolex-yz-erkek/m14-7.jpg', 'Açı 7', 6),
  ('rolex-yz-erkek-14', '/urunler/rolex-yz-erkek/m14-8.jpg', 'Açı 8', 7),
  ('rolex-yz-erkek-14', '/urunler/rolex-yz-erkek/m14-9.jpg', 'Açı 9', 8),
  ('rolex-yz-erkek-14', '/urunler/rolex-yz-erkek/m14-10.jpg', 'Açı 10', 9),
  ('rolex-yz-erkek-14', '/urunler/rolex-yz-erkek/m14-11.jpg', 'Açı 11', 10),
  ('rolex-yz-erkek-14', '/urunler/rolex-yz-erkek/m14-12.jpg', 'Açı 12', 11),
  ('rolex-yz-erkek-15', '/urunler/rolex-yz-erkek/m15-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-16', '/urunler/rolex-yz-erkek/m16-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-16', '/urunler/rolex-yz-erkek/m16-2.jpg', 'Açı 2', 1),
  ('rolex-yz-erkek-16', '/urunler/rolex-yz-erkek/m16-3.jpg', 'Açı 3', 2),
  ('rolex-yz-erkek-16', '/urunler/rolex-yz-erkek/m16-4.jpg', 'Açı 4', 3),
  ('rolex-yz-erkek-16', '/urunler/rolex-yz-erkek/m16-5.jpg', 'Açı 5', 4),
  ('rolex-yz-erkek-16', '/urunler/rolex-yz-erkek/m16-6.jpg', 'Açı 6', 5),
  ('rolex-yz-erkek-17', '/urunler/rolex-yz-erkek/m17-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-17', '/urunler/rolex-yz-erkek/m17-2.jpg', 'Açı 2', 1),
  ('rolex-yz-erkek-17', '/urunler/rolex-yz-erkek/m17-3.jpg', 'Açı 3', 2),
  ('rolex-yz-erkek-18', '/urunler/rolex-yz-erkek/m18-1.jpg', 'Açı 1', 0),
  ('rolex-yz-erkek-19', '/urunler/rolex-yz-erkek/m19-1.jpg', 'Açı 1', 0),
  ('rolex-bayan-31-1', '/urunler/rolex-bayan-31/m1-1.jpg', 'Açı 1', 0),
  ('rolex-bayan-31-2', '/urunler/rolex-bayan-31/m2-1.jpg', 'Açı 1', 0),
  ('rolex-bayan-31-3', '/urunler/rolex-bayan-31/m3-1.jpg', 'Açı 1', 0),
  ('rolex-bayan-31-3', '/urunler/rolex-bayan-31/m3-2.jpg', 'Açı 2', 1),
  ('rolex-bayan-31-3', '/urunler/rolex-bayan-31/m3-3.jpg', 'Açı 3', 2),
  ('rolex-bayan-31-3', '/urunler/rolex-bayan-31/m3-4.jpg', 'Açı 4', 3),
  ('rolex-bayan-31-3', '/urunler/rolex-bayan-31/m3-5.jpg', 'Açı 5', 4),
  ('rolex-bayan-31-3', '/urunler/rolex-bayan-31/m3-6.jpg', 'Açı 6', 5),
  ('rolex-bayan-31-3', '/urunler/rolex-bayan-31/m3-7.jpg', 'Açı 7', 6),
  ('rolex-bayan-31-4', '/urunler/rolex-bayan-31/m4-1.jpg', 'Açı 1', 0),
  ('rolex-bayan-31-4', '/urunler/rolex-bayan-31/m4-2.jpg', 'Açı 2', 1),
  ('rolex-bayan-31-4', '/urunler/rolex-bayan-31/m4-3.jpg', 'Açı 3', 2),
  ('rolex-bayan-31-4', '/urunler/rolex-bayan-31/m4-4.jpg', 'Açı 4', 3),
  ('rolex-bayan-31-4', '/urunler/rolex-bayan-31/m4-5.jpg', 'Açı 5', 4),
  ('rolex-bayan-31-4', '/urunler/rolex-bayan-31/m4-6.jpg', 'Açı 6', 5),
  ('rolex-bayan-31-4', '/urunler/rolex-bayan-31/m4-7.jpg', 'Açı 7', 6),
  ('rolex-bayan-31-4', '/urunler/rolex-bayan-31/m4-8.jpg', 'Açı 8', 7),
  ('rolex-bayan-31-4', '/urunler/rolex-bayan-31/m4-9.jpg', 'Açı 9', 8),
  ('rolex-bayan-31-5', '/urunler/rolex-bayan-31/m5-1.jpg', 'Açı 1', 0),
  ('saat-kutulari-1', '/urunler/saat-kutulari/m1-1.jpg', 'Açı 1', 0),
  ('saat-kutulari-2', '/urunler/saat-kutulari/m2-1.jpg', 'Açı 1', 0),
  ('saat-kutulari-3', '/urunler/saat-kutulari/m3-1.jpg', 'Açı 1', 0),
  ('saat-kutulari-4', '/urunler/saat-kutulari/m4-1.jpg', 'Açı 1', 0),
  ('saat-kutulari-5', '/urunler/saat-kutulari/m5-1.jpg', 'Açı 1', 0),
  ('seven-friday-1', '/urunler/seven-friday/m1-1.jpg', 'Açı 1', 0),
  ('seven-friday-1', '/urunler/seven-friday/m1-2.jpg', 'Açı 2', 1),
  ('seven-friday-1', '/urunler/seven-friday/m1-3.jpg', 'Açı 3', 2),
  ('seven-friday-1', '/urunler/seven-friday/m1-4.jpg', 'Açı 4', 3),
  ('seven-friday-1', '/urunler/seven-friday/m1-5.jpg', 'Açı 5', 4),
  ('seven-friday-1', '/urunler/seven-friday/m1-6.jpg', 'Açı 6', 5),
  ('seven-friday-2', '/urunler/seven-friday/m2-1.jpg', 'Açı 1', 0),
  ('seven-friday-3', '/urunler/seven-friday/m3-1.jpg', 'Açı 1', 0),
  ('seven-friday-4', '/urunler/seven-friday/m4-1.jpg', 'Açı 1', 0),
  ('seven-friday-5', '/urunler/seven-friday/m5-1.jpg', 'Açı 1', 0),
  ('seven-friday-5', '/urunler/seven-friday/m5-2.jpg', 'Açı 2', 1),
  ('seven-friday-6', '/urunler/seven-friday/m6-1.jpg', 'Açı 1', 0),
  ('tag-1', '/urunler/tag/m1-1.jpg', 'Açı 1', 0),
  ('tag-2', '/urunler/tag/m2-1.jpg', 'Açı 1', 0),
  ('tag-3', '/urunler/tag/m3-1.jpg', 'Açı 1', 0),
  ('tag-4', '/urunler/tag/m4-1.jpg', 'Açı 1', 0),
  ('tag-5', '/urunler/tag/m5-1.jpg', 'Açı 1', 0),
  ('tag-6', '/urunler/tag/m6-1.jpg', 'Açı 1', 0),
  ('tudor-1', '/urunler/tudor/m1-1.jpg', 'Açı 1', 0),
  ('tudor-1', '/urunler/tudor/m1-2.jpg', 'Açı 2', 1),
  ('tudor-2', '/urunler/tudor/m2-1.jpg', 'Açı 1', 0),
  ('tudor-2', '/urunler/tudor/m2-2.jpg', 'Açı 2', 1),
  ('tudor-3', '/urunler/tudor/m3-1.jpg', 'Açı 1', 0),
  ('tudor-4', '/urunler/tudor/m4-1.jpg', 'Açı 1', 0),
  ('tudor-5', '/urunler/tudor/m5-1.jpg', 'Açı 1', 0),
  ('tudor-6', '/urunler/tudor/m6-1.jpg', 'Açı 1', 0),
  ('tudor-7', '/urunler/tudor/m7-1.jpg', 'Açı 1', 0),
  ('tudor-8', '/urunler/tudor/m8-1.jpg', 'Açı 1', 0),
  ('tudor-9', '/urunler/tudor/m9-1.jpg', 'Açı 1', 0),
  ('tudor-10', '/urunler/tudor/m10-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-1', '/urunler/ulyse-nardin/m1-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-2', '/urunler/ulyse-nardin/m2-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-3', '/urunler/ulyse-nardin/m3-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-4', '/urunler/ulyse-nardin/m4-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-5', '/urunler/ulyse-nardin/m5-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-5', '/urunler/ulyse-nardin/m5-2.jpg', 'Açı 2', 1),
  ('ulyse-nardin-5', '/urunler/ulyse-nardin/m5-3.jpg', 'Açı 3', 2),
  ('ulyse-nardin-5', '/urunler/ulyse-nardin/m5-4.jpg', 'Açı 4', 3),
  ('ulyse-nardin-6', '/urunler/ulyse-nardin/m6-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-7', '/urunler/ulyse-nardin/m7-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-8', '/urunler/ulyse-nardin/m8-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-9', '/urunler/ulyse-nardin/m9-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-10', '/urunler/ulyse-nardin/m10-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-11', '/urunler/ulyse-nardin/m11-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-12', '/urunler/ulyse-nardin/m12-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-13', '/urunler/ulyse-nardin/m13-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-14', '/urunler/ulyse-nardin/m14-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-15', '/urunler/ulyse-nardin/m15-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-16', '/urunler/ulyse-nardin/m16-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-17', '/urunler/ulyse-nardin/m17-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-18', '/urunler/ulyse-nardin/m18-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-19', '/urunler/ulyse-nardin/m19-1.jpg', 'Açı 1', 0),
  ('ulyse-nardin-20', '/urunler/ulyse-nardin/m20-1.jpg', 'Açı 1', 0),
  ('versace-bayan-1', '/urunler/versace-bayan/m1-1.jpg', 'Açı 1', 0),
  ('versace-bayan-2', '/urunler/versace-bayan/m2-1.jpg', 'Açı 1', 0),
  ('versace-bayan-2', '/urunler/versace-bayan/m2-2.jpg', 'Açı 2', 1),
  ('versace-bayan-2', '/urunler/versace-bayan/m2-3.jpg', 'Açı 3', 2),
  ('versace-bayan-2', '/urunler/versace-bayan/m2-4.jpg', 'Açı 4', 3),
  ('versace-bayan-2', '/urunler/versace-bayan/m2-5.jpg', 'Açı 5', 4),
  ('versace-bayan-2', '/urunler/versace-bayan/m2-6.jpg', 'Açı 6', 5),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-1.jpg', 'Açı 1', 0),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-2.jpg', 'Açı 2', 1),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-3.jpg', 'Açı 3', 2),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-4.jpg', 'Açı 4', 3),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-5.jpg', 'Açı 5', 4),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-6.jpg', 'Açı 6', 5),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-7.jpg', 'Açı 7', 6),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-8.jpg', 'Açı 8', 7),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-9.jpg', 'Açı 9', 8),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-10.jpg', 'Açı 10', 9),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-11.jpg', 'Açı 11', 10),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-12.jpg', 'Açı 12', 11),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-13.jpg', 'Açı 13', 12),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-14.jpg', 'Açı 14', 13),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-15.jpg', 'Açı 15', 14),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-16.jpg', 'Açı 16', 15),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-17.jpg', 'Açı 17', 16),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-18.jpg', 'Açı 18', 17),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-19.jpg', 'Açı 19', 18),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-20.jpg', 'Açı 20', 19),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-21.jpg', 'Açı 21', 20),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-22.jpg', 'Açı 22', 21),
  ('versace-bayan-3', '/urunler/versace-bayan/m3-23.jpg', 'Açı 23', 22),
  ('versace-bayan-4', '/urunler/versace-bayan/m4-1.jpg', 'Açı 1', 0),
  ('versace-bayan-4', '/urunler/versace-bayan/m4-2.jpg', 'Açı 2', 1),
  ('versace-erkek-1', '/urunler/versace-erkek/m1-1.jpg', 'Açı 1', 0),
  ('versace-erkek-2', '/urunler/versace-erkek/m2-1.jpg', 'Açı 1', 0),
  ('versace-erkek-3', '/urunler/versace-erkek/m3-1.jpg', 'Açı 1', 0),
  ('versace-erkek-4', '/urunler/versace-erkek/m4-1.jpg', 'Açı 1', 0),
  ('versace-erkek-4', '/urunler/versace-erkek/m4-2.jpg', 'Açı 2', 1),
  ('versace-erkek-5', '/urunler/versace-erkek/m5-1.jpg', 'Açı 1', 0),
  ('versace-erkek-5', '/urunler/versace-erkek/m5-2.jpg', 'Açı 2', 1),
  ('versace-erkek-5', '/urunler/versace-erkek/m5-3.jpg', 'Açı 3', 2),
  ('versace-erkek-5', '/urunler/versace-erkek/m5-4.jpg', 'Açı 4', 3),
  ('versace-erkek-5', '/urunler/versace-erkek/m5-5.jpg', 'Açı 5', 4),
  ('versace-erkek-5', '/urunler/versace-erkek/m5-6.jpg', 'Açı 6', 5),
  ('versace-erkek-5', '/urunler/versace-erkek/m5-7.jpg', 'Açı 7', 6),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-1.jpg', 'Açı 1', 0),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-2.jpg', 'Açı 2', 1),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-3.jpg', 'Açı 3', 2),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-4.jpg', 'Açı 4', 3),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-5.jpg', 'Açı 5', 4),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-6.jpg', 'Açı 6', 5),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-7.jpg', 'Açı 7', 6),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-8.jpg', 'Açı 8', 7),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-9.jpg', 'Açı 9', 8),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-10.jpg', 'Açı 10', 9),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-11.jpg', 'Açı 11', 10),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-12.jpg', 'Açı 12', 11),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-13.jpg', 'Açı 13', 12),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-14.jpg', 'Açı 14', 13),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-15.jpg', 'Açı 15', 14),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-16.jpg', 'Açı 16', 15),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-17.jpg', 'Açı 17', 16),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-18.jpg', 'Açı 18', 17),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-19.jpg', 'Açı 19', 18),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-20.jpg', 'Açı 20', 19),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-21.jpg', 'Açı 21', 20),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-22.jpg', 'Açı 22', 21),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-23.jpg', 'Açı 23', 22),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-24.jpg', 'Açı 24', 23),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-25.jpg', 'Açı 25', 24),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-26.jpg', 'Açı 26', 25),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-27.jpg', 'Açı 27', 26),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-28.jpg', 'Açı 28', 27),
  ('versace-erkek-6', '/urunler/versace-erkek/m6-29.jpg', 'Açı 29', 28),
  ('versace-erkek-7', '/urunler/versace-erkek/m7-1.jpg', 'Açı 1', 0),
  ('versace-erkek-8', '/urunler/versace-erkek/m8-1.jpg', 'Açı 1', 0),
  ('versace-erkek-9', '/urunler/versace-erkek/m9-1.jpg', 'Açı 1', 0),
  ('versace-erkek-10', '/urunler/versace-erkek/m10-1.jpg', 'Açı 1', 0),
  ('versace-erkek-10', '/urunler/versace-erkek/m10-2.jpg', 'Açı 2', 1),
  ('washaron-1', '/urunler/washaron/m1-1.jpg', 'Açı 1', 0),
  ('washaron-1', '/urunler/washaron/m1-2.jpg', 'Açı 2', 1),
  ('washaron-1', '/urunler/washaron/m1-3.jpg', 'Açı 3', 2),
  ('washaron-2', '/urunler/washaron/m2-1.jpg', 'Açı 1', 0),
  ('washaron-3', '/urunler/washaron/m3-1.jpg', 'Açı 1', 0),
  ('washaron-4', '/urunler/washaron/m4-1.jpg', 'Açı 1', 0),
  ('washaron-5', '/urunler/washaron/m5-1.jpg', 'Açı 1', 0),
  ('washaron-6', '/urunler/washaron/m6-1.jpg', 'Açı 1', 0),
  ('washaron-7', '/urunler/washaron/m7-1.jpg', 'Açı 1', 0),
  ('washaron-8', '/urunler/washaron/m8-1.jpg', 'Açı 1', 0),
  ('washaron-9', '/urunler/washaron/m9-1.jpg', 'Açı 1', 0),
  ('washaron-10', '/urunler/washaron/m10-1.jpg', 'Açı 1', 0)
) as v(slug, url, label, sort_order)
join products p on p.slug = v.slug;
